version: '3.4'

services:

  caddy:
    image: abiosoft/caddy:latest
    environment:
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/root/.caddy

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock        
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data  

volumes:
  portainer:
    external: true
  certs:
    external: true

networks:
  default:
    driver: overlay
    attachable: true