version: '3.4'

services:

  caddy:    
    configs:
      - source: CaddyfileProd
        target: /etc/Caddyfile   

  logdna:
    image: logdna/logspout:latest
    hostname: conrado.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOGDNA_KEY=${LOGDNA_KEY}

configs:
  CaddyfileProd: 
    file: ./config/Caddyfile.prod